doctrine:
  dbal:
    use_savepoints: true

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
    url: 'mysql://%env(string:DB_USER)%:%env(string:DB_PASSWORD)%@%env(string:DB_HOST)%:3306/%env(string:DB_NAME)%?serverVersion=9.0&charset=utf8mb4'

    types:
      edibleType: App\Edible\Infrastructure\Doctrine\EdibleTypeType
      unit: App\Edible\Infrastructure\Doctrine\UnitType

  orm:
    auto_generate_proxy_classes: true
    controller_resolver:
      auto_mapping: false
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      # https://stackoverflow.com/questions/56471926/how-to-configure-multiple-orm-mappings-doctrine-outside-the-bundle
      App\Edible\Domain:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Edible/Infrastructure/Doctrine'
        prefix: App\Edible\Domain
        alias: Edible
        mapping: true
      App\Edible\Domain\Fruit:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Edible/Infrastructure/Doctrine/Fruit'
        prefix: App\Edible\Domain\Fruit
        alias: Fruit
        mapping: true
      App\Edible\Domain\Vegetable:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Edible/Infrastructure/Doctrine/Vegetable'
        prefix: App\Edible\Domain\Vegetable
        alias: Vegetable
        mapping: true

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: ''

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system