name: roadsurfer-test
services:
  php:
    build:
      dockerfile: Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    tty: true
    volumes:
      - ../:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'