name: roadsurfer-test
services:
  php:
    build:
      dockerfile: Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    tty: true
    volumes:
      - ../:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - roadsurfer-network
  mysql:
    image: mysql:9
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ../var/db:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - roadsurfer-network
networks:
  roadsurfer-network: