name: PHPStan

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run PHPStan checks
        uses: php-actions/phpstan@v3
